services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "8000:8000"
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY
      - OPENAI_API_ENDPOINT
      
      # Qdrant Configuration
      - QDRANT_URL
      - QDRANT_API_KEY
      
      # Phoenix/Arize Configuration
      - PHOENIX_API_KEY
      - PHOENIX_COLLECTOR_ENDPOINT
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Optional: Add volumes for persistent data or logs
    # volumes:
    #   - ./logs:/app/logs
    
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    name: backend-network